#!/usr/bin/env ruby

require 'fileutils'
require 'rack/test'
require 'slim_cms/sitemap'
require File.expand_path('app.rb', Dir.pwd)

# TODO: fix broken links
# TODO: write tests
# TODO: archive old files

class StaticGenerator
  include Rack::Test::Methods

  def app
    Rack::Builder.parse_file(File.expand_path('config.ru', Dir.pwd)).first
  end

  def crawl_sitemap(sitemap)
    sitemap.keys.each do |path|
      meta = sitemap[path]

      output_path = meta[:directory] ? path + '/index.html' : path + '.html'
      output_path.gsub!('//', '/')

      write_file(output_path, get(path).body)

      crawl_sitemap(meta[:children]) if meta[:children]
    end
  end

  def write_file(path, content)
    output_path = Pathname.new(File.join(Dir.pwd, 'public', path))
    output_dirname = output_path.dirname

    unless File.directory?(output_dirname)
      FileUtils.mkdir_p(output_dirname)
    end

    File.open(output_path, 'w') do |file|
      file.write(content)
    end
  end

  def write_sitemap_xml
    write_file('sitemap.xml', get('sitemap.xml').body)
  end

  def write_stylesheets
    Pathname.new('assets/stylesheets').children.each do |child_path|
      output_path = child_path.sub('assets/', '').sub('.scss', '.css')

      write_file('stylesheets/' + output_path, get(output_path).body) if Pathname.new(output_path).basename.to_s.start_with?('_')
    end
  end
end

generator = StaticGenerator.new
generator.crawl_sitemap(SlimCms::Sitemap.new(Sinatra::Application.root, 'config', 'views').generate)
generator.write_stylesheets
generator.write_sitemap_xml
