#!/usr/bin/env ruby

require 'slim_cms/static_generator'
require 'slim_cms/sitemap'
require File.expand_path('app.rb', Dir.pwd)

generator = SlimCms::StaticGenerator.new
generator.generate_views(SlimCms::Sitemap.new(Sinatra::Application.root, 'config', 'views').generate)
generator.generate_stylesheets
generator.generate_sitemap_xml
generator.generate_robots_txt
